version: "3.7"

networks:
    docker.network:
        driver: bridge

services:
    web:
        image: nginx:latest
        networks:
            - docker.network
        ports:
            - "8080:80"
        volumes:
            - ./ibexa:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    php-fpm:
        build: docker/php-fpm
        networks:
            - docker.network
        volumes:
            - ./ibexa:/var/www/html
    redis:
        image: bitnami/redis:latest
        restart: unless-stopped
        tty: true
        networks:
            - docker.network
        ports:
            - "6379:6379"
    postgres:
        image: postgres:14-alpine
        restart: unless-stopped
        tty: true
        networks:
            - docker.network
        ports:
            - "5432:5432"
        volumes:
            - "./docker/postgres/dbdata:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-development}
